{application,arm_audio,
             [{modules,['Elixir.ArmAudio','Elixir.ArmAudio.Decoder',
                        'Elixir.ArmAudio.Piper','Elixir.ArmAudio.SileroVAD']},
              {optional_applications,[rustler]},
              {applications,[kernel,stdlib,elixir,logger,rustler,
                             rustler_precompiled,nx,arm_ai,nx_arm,
                             arm_nx_primitives,arm_vision]},
              {description,"Nx-tensor audio I/O + model wrappers on ARM CPUs (Silero VAD / Piper TTS via tract-onnx, symphonia decode, rubato resample)"},
              {registered,[]},
              {vsn,"0.1.0"}]}.
