{application,vision,
             [{modules,['Elixir.Vision','Elixir.Vision.Backend',
                        'Elixir.Vision.Detection','Elixir.Vision.Face',
                        'Elixir.Vision.Image','Elixir.Vision.OCR',
                        'Elixir.Vision.Onnx','Elixir.Vision.Preprocess',
                        'Elixir.Vision.StableDiffusion','Elixir.Vision.YOLO']},
              {optional_applications,[rustler]},
              {applications,[kernel,stdlib,elixir,logger,nx,nx_primitives,
                             rustler,rustler_precompiled]},
              {description,"Generic Nx-tensor vision model wrappers (YOLO / OCR / Face / generic ONNX) with a pluggable native backend (see `Vision.Backend`)."},
              {registered,[]},
              {vsn,"0.1.0"}]}.
