{application,arm_vision,
             [{modules,['Elixir.ArmVision','Elixir.ArmVision.Detection',
                        'Elixir.ArmVision.Face','Elixir.ArmVision.Image',
                        'Elixir.ArmVision.OCR','Elixir.ArmVision.Onnx',
                        'Elixir.ArmVision.Preprocess',
                        'Elixir.ArmVision.StableDiffusion',
                        'Elixir.ArmVision.YOLO']},
              {optional_applications,[rustler]},
              {applications,[kernel,stdlib,elixir,logger,rustler,
                             rustler_precompiled,nx,arm_ai,nx_arm,
                             arm_nx_primitives]},
              {description,"Nx-tensor vision model wrappers + preprocessing on ARM CPUs (YOLO / OCR / Face / generic ONNX / Stable Diffusion via tract-onnx)"},
              {registered,[]},
              {vsn,"0.1.0"}]}.
