{application,infer_vision,
             [{modules,['Elixir.InferVision','Elixir.InferVision.Backend',
                        'Elixir.InferVision.Detection',
                        'Elixir.InferVision.Face','Elixir.InferVision.Image',
                        'Elixir.InferVision.OCR','Elixir.InferVision.Onnx',
                        'Elixir.InferVision.Preprocess',
                        'Elixir.InferVision.StableDiffusion',
                        'Elixir.InferVision.YOLO']},
              {optional_applications,[rustler]},
              {applications,[kernel,stdlib,elixir,logger,nx,nx_primitives,
                             rustler,rustler_precompiled]},
              {description,"Generic Nx-tensor vision model wrappers (YOLO / OCR / Face / generic ONNX) with a pluggable native backend (see `InferVision.Backend`)."},
              {registered,[]},
              {vsn,"0.1.0"}]}.
